[package]
name = "jadis"
version = "0.1.0"
authors = ["Andrew Binstock (@platypusguy)"]
homepage = "https://github.com/platypusguy/jadis"
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
